name: team_management_app
description: Een Flutter-app voor het beheren van teams en evenementen.

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.0
  google_maps_flutter: ^2.3.0
  http: ^0.13.6
  intl: ^0.17.0
  flutter_local_notifications: ^15.0.0
  url_launcher: ^6.1.10
  qr_flutter: ^4.0.0
  provider: ^6.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
